# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - cmp229-incidents-frontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://incidentsfrontend.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_3582b196fdc646a4b45c3c00b4972c1e }}
        password: ${{ secrets.AzureAppService_ContainerPassword_c3b3b174f8cb44708575cd3fc5dd5133 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: incidentsfrontend.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_3582b196fdc646a4b45c3c00b4972c1e }}/frontend:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'cmp229-incidents-frontend'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_d2287e1b4ac24d05b73bfcca4923191c }}
        images: 'incidentsfrontend.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_3582b196fdc646a4b45c3c00b4972c1e }}/frontend:${{ github.sha }}'